#include "hash_tables.h"
/**
 * key_index - A function that returns the key index from a key string
 *
 * @size: size of the hash table
 * @key: Key generated by the hash_djb2 function
 *
 * Return: Key index
 */
unsigned long int key_index(const unsigned char *key, unsigned long int size)
{
	unsigned long int hash = hash_djb2(key), index_key;

	index_key = hash % size;
	return (index_key);
}
